[32m2024-09-17 16:57:05 +0200[0m - dagster - [34mDEBUG[0m - staging_pipeline - f3830895-c551-4068-9be3-9f86bdbb3f23 - 95490 - LOGS_CAPTURED - Started capturing logs in process (pid: 95490).
[32m2024-09-17 16:57:05 +0200[0m - dagster - [34mDEBUG[0m - staging_pipeline - f3830895-c551-4068-9be3-9f86bdbb3f23 - 95490 - soda_UI_check - STEP_START - Started execution of step "soda_UI_check".
[32m2024-09-17 16:57:05 +0200[0m - dagster - [34mINFO[0m - staging_pipeline - f3830895-c551-4068-9be3-9f86bdbb3f23 - soda_UI_check - Request successful
[32m2024-09-17 16:57:16 +0200[0m - dagster - [34mINFO[0m - staging_pipeline - f3830895-c551-4068-9be3-9f86bdbb3f23 - soda_UI_check - Scan failed with status: completedWithErrors
[32m2024-09-17 16:57:16 +0200[0m - dagster - [34mERROR[0m - [31mstaging_pipeline - f3830895-c551-4068-9be3-9f86bdbb3f23 - 95490 - soda_UI_check - STEP_FAILURE - Execution of step "soda_UI_check" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "soda_UI_check"::

dagster._check.functions.ParameterCheckError: Param "passed" is not a bool. Got 'completed' which is type <class 'str'>.

Stack Trace:
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/dbt-project/dagster/pipeline/assets.py", line 598, in soda_UI_check
    AssetCheckResult(
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_core/definitions/asset_check_result.py", line 74, in __new__
    passed=check.bool_param(passed, "passed"),
  File "/Users/hazem/Documents/Soda/GitHub/soda-dagster-demo/.venv/lib/python3.9/site-packages/dagster/_check/functions.py", line 66, in bool_param
    raise _param_type_mismatch_exception(obj, bool, param_name, additional_message)
[0m
